// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIkktlLvuk77DS99EeXR0UoW2ny8cphA',
    appId: '1:128707766300:web:3972091b93f597408b57d9',
    messagingSenderId: '128707766300',
    projectId: 'aurify-e693c',
    authDomain: 'aurify-e693c.firebaseapp.com',
    storageBucket: 'aurify-e693c.firebasestorage.app',
    measurementId: 'G-D43446HDG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdlNUYTWMockuAMK8X1C2hBukQH7Sqsc',
    appId: '1:128707766300:android:41edf6241012de758b57d9',
    messagingSenderId: '128707766300',
    projectId: 'aurify-e693c',
    storageBucket: 'aurify-e693c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW61QBePfcxXTpHDj8pFz7d2tiw6DzDS0',
    appId: '1:128707766300:ios:565acc65db18affb8b57d9',
    messagingSenderId: '128707766300',
    projectId: 'aurify-e693c',
    storageBucket: 'aurify-e693c.firebasestorage.app',
    iosBundleId: 'com.example.aurifyTask',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW61QBePfcxXTpHDj8pFz7d2tiw6DzDS0',
    appId: '1:128707766300:ios:565acc65db18affb8b57d9',
    messagingSenderId: '128707766300',
    projectId: 'aurify-e693c',
    storageBucket: 'aurify-e693c.firebasestorage.app',
    iosBundleId: 'com.example.aurifyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZIkktlLvuk77DS99EeXR0UoW2ny8cphA',
    appId: '1:128707766300:web:c708de34e8b63a838b57d9',
    messagingSenderId: '128707766300',
    projectId: 'aurify-e693c',
    authDomain: 'aurify-e693c.firebaseapp.com',
    storageBucket: 'aurify-e693c.firebasestorage.app',
    measurementId: 'G-0D3DG6XF8M',
  );
}
